apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigs.saas.openshift.io
spec:
  group: saas.openshift.io
  names:
    kind: ClusterConfig
    listKind: ClusterConfigList
    plural: clusterconfigs
    singular: clusterconfig
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        config:
          properties:
            role:
              type: string
            address:
              type: string
            host:
              properties:
                address:
                  type: string
                secretRef:
                  properties:
                    name:
                      type: string
            members:
              type: array
              items:
                properties:
                  address:
                    type: string
                  secretRef:
                    properties:
                      name:
                        type: string
          required:
            - role
  version: v1alpha1
