apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-next
spec:
  replicas: 1
  selector:
    matchLabels:
      name: saas-next
  template:
    metadata:
      labels:
        name: saas-next
    spec:
      serviceAccountName: saas-next
      containers:
        - name: saas-next
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "saas-next"
