apiVersion: saas.openshift.io/v1alpha1
kind: ClusterConfig
metadata:
  name: saas-next-clusterconfig
  namespace: saas-control-plane
spec:
  config:
    role: host
    apiAddress: https://192.168.42.45:8443